name: Pylint

on: [ push ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pygame
          pip install pywin32
          pip install winshell
          pip install Pillow
          pip install imtools
          pip install infi.systray
          pip install keyboard
          pip install pyinstaller==3.5
      - name: Analysing the code with pylint
        run: |
          pylint manager.py main.py animator.py blur.py exe_layer.py GWSL_ssh.py iset.py OpticUI.py wsl_tools.py
       - name: Building GWSL_service...
        run: |
          echo "pyinstaller"
          #python pyinstaller.....
      - name: Building GWSL...
        run: |
          echo "pyinstaller"
      - name: Merging Results...
        run: |
          echo "pyinstaller"
      - name: Copying Assets...
        run: |
          echo "pyinstaller"
      - name: Upload
        run: git add ${{github.workspace}} && git commit -m "Uploaded build" && git push  
